### ISSUE TITLE
ACT provider ID

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#100]
Add provider ID back to ACT extract, as it is part of the PK.

**Comment by DarrenWHenderson** [comment]
I have tested both of the below methods at our site. Both were able to pass the primary key check after implementation, so uniqueness was maintained to my satisfaction. Additionally, I checked for collision. Our site is fairly small, so luckily our provider_ids never hashed/checksumed out to the same value in md5/checksum. I think in md5 it's very unlikely, even at a large site. At a large site, I could see checksum having at least 1 collision in the dataset. 

```CONVERT(VARCHAR(50),HASHBYTES('MD5',provider_id),2) AS provider_id```

```CONVERT(VARCHAR(50),CHECKSUM(provider_id),2) AS provider_id```

```
/* Collision testing */

;with md5collision_test as (
select provider_id, CONVERT(VARCHAR(50),HASHBYTES('MD5',provider_id),2) as provider_md5
from n3c.observation_fact
group by provider_id
)
, collide as (
select provider_md5
from md5collision_test
group by provider_md5
having count(provider_id) > 1
)
select provider_id, provider_md5
from md5collision_test
where provider_md5 in (select provider_md5 from collide)


;with checksumcollision_test as (
select provider_id, CONVERT(VARCHAR(50),CHECKSUM(provider_id),2) as provider_checksum
from n3c.observation_fact
group by provider_id
)
, collide as (
select provider_checksum
from checksumcollision_test
group by provider_checksum
having count(provider_id) > 1
)
select provider_id, provider_checksum
from checksumcollision_test
where provider_checksum in (select provider_checksum from collide)
```

**Comment by DarrenWHenderson** [comment]
Another thought about hashing the provider_id to keep it in the primary key. An extremely motivated attacker could produce a rainbow table to attack the hash if the provider_id was not salted prior to hashing. I think the code should instruct individual sites to create a custom salt of some length to concatenate to their provider_ids (after casting them to strings if necessary), prior to the hashbytes, or checksum, process.
