### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by robertwinterVUMC** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#106]
Greetings - for our first push of data, we would like to send it without all of the required data elements because a few of them have not been completed yet. Is there any issue with us pushing the first couple without OBSERVATION_PERIOD table, nor SPECIMEN_CONCEPT_ID and TYPE_CONCEPT_ID?

**Comment by empfff** [comment]
Hi! Of the items you mentioned, the second and third will not be a problem to leave out for now. The OBSERVATION_PERIOD table, however, is a part of the phenotyping process, so you will want to have that. OBSERVATION_PERIOD is a derived table--we should be able to provide you with scripts to generate that if that would be helpful. Just let us know!

**Comment by robertwinterVUMC** [comment]
Greetings - thank you for the offer of providing the scripts to generate the OBSERVATION_PERIOD table. Can you send them to an email? robert.winter@vumc.org

**Comment by empfff** [comment]
Email sent. Also, just to close the loop, I misspoke above when I said TYPE_CONCEPT_ID is not required; the harmonization team actually needs that field. I provided additional detail in the email I just sent. Thanks!
