### ISSUE TITLE
B97.21

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#11]
Suggestion to downgrade B97.21 ICD-10 code to a weak positive on or after 4/1/2020, when the "real" covid ICD-10 code was released for use. This would be the same rule that we applied to B97.29.

**Comment by remurphymd** [comment]
Hmmm...see, I think B97.21 would be weak positive but B97.29 would be strong posiitve. That WAS the recommended code from mid-January through 4/1/20, when used with another respiratory ICD-10.

**Comment by empfff** [comment]
Both codes are strong until 4/1/2020. It was decided to make them weak on or after 4/1/2020, when the "real" came out, because an OHDSI Studyathon found them to be a big source of false positives. Being a weak dx code still gets a lot of people in the cohort--it just requires them to have a second weak code as well.
