### ISSUE TITLE
Consistent Date format should be used across all files

### ISSUE THREAD

**Issue by srn0133** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#114]
The expected date format is yyyy-mm-dd (hh24:mi:ss) across all date fields. But receiving few files with format dd-mon-yy.

**Comment by empfff** [comment]
We need more specifics on which site(s) you're seeing this issue from in order to help. You can email this information to me, or message me on Slack. Thanks!

**Comment by empfff** [comment]
This has been fixed in the place you mentioned you were seeing a problem--that site's future payloads will not have the issue. Let us know if you see any more examples.
