### ISSUE TITLE
Multi-fact model

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#12]
For the ACT phenotype code--do we need to accommodate sites that use the multi-fact model? I know we can't know their table names, so no point in writing out code for it exactly, but maybe add comments indicating where sites would swap in their specific table names in the code?

**Comment by mim18** [comment]
Will have a path based query Monday 4/27 that should accommodate the multi-fact table.
