### ISSUE TITLE
Update Phenotype code for 2.1

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#123]
See pre-release documentation on the Wiki for (1) new LOINC codes, (2) removal of the procedure table (which will require removal of the procedure logic in the code). Please make changes in the phenotype-21 branch, not master.

Good idea to complete the manifest automation work (see #115 ) at the same time as making this change.

**Comment by empfff** [comment]
Done for PCORnet

**Comment by kmkostka** [comment]
Done for OMOP: all code is inside branch ````phenotype-21````.
