### ISSUE TITLE
ACT Oracle Extract Provider Hash Syntax Error

### ISSUE THREAD

**Issue by bjbush** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#126]
Line 390 of N3C_extract_act_oracle.sql references a table aliased as "ofct" -- the OBSERVATION_FACT table is not aliased in this query and causes an error -- cx_Oracle.DatabaseError: ORA-00904: "OFCT"."PROVIDER_ID": invalid identifier.

Current line 390: standard_hash(ofct.PROVIDER_ID,'MD5') AS provider_id,

Correct or remove the table prefix.

**Comment by empfff** [comment]
Fixed!
