### ISSUE TITLE
ACT Oracle Extract Ambiguous Concept_Cd Syntax Error

### ISSUE THREAD

**Issue by bjbush** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#127]
Line 389 of N3C_extract_act_oracle.sql attempts to select "concept_cd" without a table prefix, but the updated SQL statement includes two tables with this field name (n3c_concepts and observation_fact).  This causes an error -- cx_Oracle.DatabaseError: ORA-00918: column ambiguously defined.

Current line 389: concept_cd,

Add "observation_fact." as the table prefix.

**Comment by empfff** [comment]
Fixed!
