### ISSUE TITLE
OMOP Vocab Update Needed

### ISSUE THREAD

**Issue by kmkostka** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#13]
@cukarthik  and I need to coordinate with the OMOP Vocabulary team to add the following new source_concepts:
94547-7	SARS-CoV-2 IgG + IgM, serum or plasma
94558-4	SARS-CoV-2 Ag, respiratory specimen
94559-2	SARS-CoV-2 ORF1ab region, respiratory specimen
94562-6	SARS-CoV-2 IgA, serum or plasma
94563-4	SARS-CoV-2 IgG, serum or plasma
94564-2	SARS-CoV-2 IgM, serum or plasma
94565-9	SARS-CoV-2 RNA, nasopharyngeal specimen
94639-2	SARS-CoV-2 ORF1ab region, unspecified specimen
94640-0	SARS-CoV-2 S gene, respiratory specimen
94641-8	SARS-CoV-2 S gene, unspecified specimen
94642-6	SARS-CoV-2 S gene, respiratory specimen
94643-4	SARS-CoV-2 S gene, unspecified specimen
94644-2	SARS-CoV-2 ORF1ab region, respiratory specimen
94645-9	SARS-CoV-2 RdRp gene, unspecified specimen
94646-7	SARS-CoV-2 RdRp gene, respiratory specimen
94647-5	SARS-related CoV, unspecified specimen
94660-8	SARS-CoV-2 RNA, serum/plasma
94661-6	SARS-CoV-2 antibody interpretation

Current phenotype will be updated as these are included in OMOP vocabularies.

**Comment by cgreich** [comment]
Will tackle tomorrow.

**Comment by dimshitc** [comment]
On it.
I noticed that these codes were taken from https://loinc.org/prerelease/
The release will be later this week. We'll let you know once it's done.

**Comment by kmkostka** [comment]
Released on 4/29.
