### ISSUE TITLE
Add date shift elements to MANIFEST file

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#134]
Change can wait until phenotype 2.2, adding ticket as reminder. Will add details of what's needed shortly.

**Comment by empfff** [comment]
New column SHIFT_DATE_YN. 
Add new column to table definition in extract file.
For exporters, add new parameter to pass the value.

**Comment by empfff** [comment]
Let's add one more column for those sites who do know their day shift count: MAX_SHIFT_NUM_DAYS

**Comment by empfff** [comment]
Done for PCORnet

**Comment by marshallclark** [comment]
added date shift params to python exporter
