### ISSUE TITLE
Cast to timestamps, not dates

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#139]
With the exception of the birth date field, which we are purposely obfuscating with a TO_CHAR, we need to make sure we are consistent in all extracts when we are casting date fields. We should be casting all to timestamp, not date, so as to preserve the time _if there is a time to be preserved._

Need to do this for all extract scripts for all models, though some may be doing this already. Please check your scripts to see how  you're currently handling.

**Comment by LoraLingrey-TriNetX** [comment]
TriNetX extracts are already converting any data stored just as dates to be date/time.

**Comment by kmkostka** [comment]
@mim18 pushed fix in last night for ACT. I just pushed fix in for OMOP.

**Comment by empfff** [comment]
PCORnet also complete.
