### ISSUE TITLE
ICD-10 code addition

### ISSUE THREAD

**Issue by smeystre** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#14]
The WHO also created an emergency ICD-10 code for COVID-19 diagnoses without lab confirmation: U07.2. https://www.who.int/classifications/icd/covid19/en/
Should it be added to the phenotype of suspected positive cases as strong positive code?

**Comment by remurphymd** [comment]
Forgive me if not proper for me to "vote"--I just joined the Github after some initial comments on the shared document--but yes, I would support the idea od U07.2 as a strong positive.

**Comment by empfff** [comment]
U07.2 is part of ICD-10, but not part of ICD-10-CM; U07.1 is in both. The former will never appear in an American EHR, though the latter will. See the link here for further explanation: https://www.aha.org/fact-sheets/2020-03-30-frequently-asked-questions-regarding-icd-10-cm-coding-covid-19

Essentially, it would not hurt to add this code, but based on our understanding it will never match a patient. Very open to correction if others have differing information.

**Comment by remurphymd** [comment]
So then is our program only limited to the US? If we have any international users, we might to include or acknowledge,

**Comment by empfff** [comment]
The sites in this particular collaborative will all be US sites. There was a discussion a couple of weeks back about excluding international codes (for now, anyhow).
