### ISSUE TITLE
Code updates for Phenotype 2.2

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#142]
For the non-OMOPians: Please remove the LOINC codes that are now struck through in the new phenotype from your code. For the OMOP-ians: Please do that, and also add the OMOP extension codes wherever they go in your code.

Also remember to update the hardcoded "2.1" to "2.2" in the phenotype version variable.

**Comment by empfff** [comment]
Done for PCORnet on Phenotype 2.2 branch

**Comment by mim18** [comment]
done for ACT on phenotype 2.2 branch
