### ISSUE TITLE
Fix act-phenotype-mssql script

### ISSUE THREAD

**Issue by uthealth-rja** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#148]
The act-phenotype-mssql script did not run for me. I have submitted a fix pull request and tested to make sure it populates the table.

**Comment by mim18** [comment]
Where did you put the pull request?

**Comment by uthealth-rja** [comment]
https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/pull/147
Thanks.
