### ISSUE TITLE
ACT acquisition script

### ISSUE THREAD

**Issue by hsolbrig** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#15]
For sites that have the [ACT i2b2 phenotype](https://github.com/shyamvis/covid-phenotyping/), wouldn't it make sense to start with a query like:

```sql
SELECT * FROM observation_fact WHERE concept_cd in 
     (SELECT concept_cd from concept_dimension where concept_path like '
      \\ACT\\UMLS_C0031437\\SNOMED_3947185011\\%');
```

This would catch updates to the phenotype and automagically include synthetic types as well as local mapping.  If we wanted to use the local mappings, it would also be necessary to add something of the form:

```sql
SELECT * from concept_dimension where concept_path like 
'\\ACT\\UMLS_C0031437\\SNOMED_3947185011\\%';
```

**Comment by empfff** [comment]
Determined that this will be addressed by Michele's new path query, to be released Monday 4/27.
