### ISSUE TITLE
Latest Phenotype LOINC Code Description has a Mistake

### ISSUE THREAD

**Issue by tannerzhang** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#151]
95125-1 the description for the code is  SARS-CoV-2 (COVID-19) IgA+IgM [Presence] in Serum or Plasma by Immunoassay. The table is wrong.

**Comment by pambanning** [comment]
The value set provided by 3M HDD team has the correct description for 95125-1. I thought these were being uploaded from the value sets? Is the table manually populated instead (that introduces risk, in my opinion). Latest set provided 10/30/20.

**Comment by empfff** [comment]
Thanks for the catch, this will be fixed in the next phenotype (coming soon).
