### ISSUE TITLE
ACT/Oracle Phenotype 3.0 - Typo in select syntax

### ISSUE THREAD

**Issue by bjbush** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#161]
Replace "a" with "as"

https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/blob/fcb3c2474e06b11ca7422112816a7d65bd8c344a/PhenotypeScripts/N3C_phenotype_act_oracle.sql#L750

**Comment by mim18** [comment]
fixed
