### ISSUE TITLE
We're using up the buddies

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#162]
As discussed on standup--for phenotype 3.1, we need to exclude cases who already have buddies assigned from the loop that assigns buddies in the phenotype script. Thanks to @LoraLingrey-TriNetX for the catch.

**Comment by marshallclark** [comment]
I think i have a fix.  i created branch buddy-saver. @empfff , @mim18  need a code review.  look at phenotype for pcornet oracle sql to see the change.  search for "BUDDY-SAVER" twice in code.  one line addition below each BUDDY-SAVER comment

**Comment by empfff** [comment]
Consolidated into #181
