### ISSUE TITLE
Script N3C_phenotype_omop_oracle.sql is not an Oracle script and does not run in Oracle.

### ISSUE THREAD

**Issue by carlsd00** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#165]
The code in script N3C_phenotype_omop_oracle.sql appears to be a copy (or close to a copy) of the MSSQL script.  

Even the comment block says "N3C Phenotype 3.0 - OMOP MSSQL
Author: Robert Miller (Tufts), Emily Pfaff (UNC)"

As coded, the script will not run on an Oracle server.
Specifically, the update statements beginning at line 904 -- Match #1 - age, sex, race, ethnicity are not coded for Oracle and appear to be code for MSSQL.
Please post the Oracle version of the script.

**Comment by empfff** [comment]
Thanks! It is an Oracle script (despite the comment at the top--that's an artifact of the SQL Render utility we use), but you're right that the UPDATE syntax did not translate appropriately. We will get a fix in by tomorrow, and thanks again for the catch.

**Comment by empfff** [comment]
We believe this is fixed, let us know if you see otherwise!
