### ISSUE TITLE
bigquery/OMOP: phenotype SQL: Date_diff syntax incorrect

### ISSUE THREAD

**Issue by mgkahn** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#169]
1. Change datediff() to date_diff()
2. Change arguments from [date part, date, date] to [date, date, date part]
3. Cast birth_datetime into date since date_diff only accepts dates, not date times (eg. cast(birthdatetime as DATE))

**Comment by empfff** [comment]
This has been corrected, thanks!
