### ISSUE TITLE
Phenotype picks up lots of children

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#17]
Thought for future versions--we have reports from UNC and UTH that the phenotype picks up a disproportionate number of children. This may not be an issue, as we know there will be many false positives in the mix, but worth thinking about whether we need to add some criteria to narrow down the number of kids that qualify.

**Comment by mim18** [comment]
Agree. I was comparing it to the ACT diagnosis codes to determine if I should modify the ACT_COVID ontology and there were several instances where I was not sure it was appropriate. 
a) Codes where there actually are no children. Ex J80, J40 
b) Codes where the children are specified and not SARS or coronavirus related. Ex. J20 .0-.7 have specific sources like rhinovirus, strep, echovirus. Do we want all of those or just .8 and .9 NOS

**Comment by empfff** [comment]
Large phenotype group determined that we should NOT weight the algorithm against children, as there may be important research questions around this population.
