### ISSUE TITLE
bigquery/OMOP: sex/hispanic/race data type confusion

### ISSUE THREAD

**Issue by mgkahn** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#170]
Three tables define sex, hispanic, race as STRING. 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/3923918/102282230-84bbbf00-3eed-11eb-94ce-e6a395ea2432.png">

SQL is inserting INT64 concept_id into STRING sex field (same with hispanic, race): 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/3923918/102282365-bc2a6b80-3eed-11eb-93ab-42e8ed8969eb.png">

In bigquery, errors w/o explicit cast.
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/3923918/102282271-93a27180-3eed-11eb-8e74-378fe7236ae5.png">

**Comment by empfff** [comment]
Fixed this in the GBQ script, thanks.
