### ISSUE TITLE
PhenotypeScripts: OMOP SQL bug?

### ISSUE THREAD

**Issue by mgkahn** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#172]
Present in all OMOP versions of the PhenotypeScript preventing completion of Phenotype 3.0 cohort:

Table **n3c_case_cohort** does not have field named **case_person_id** but subquery on line 833 (in bigquery script) references **n3c_case_cohort.case_person_id**. Should this subquery reference **n3c_control_map** which does that this field defined?

<img width="838" alt="image" src="https://user-images.githubusercontent.com/3923918/102395218-0ff18f00-3f98-11eb-8354-40b37e1c1982.png">

<img width="625" alt="image" src="https://user-images.githubusercontent.com/3923918/102395271-226bc880-3f98-11eb-993e-18b1d1ffac23.png">

**Comment by mgkahn** [comment]
Similar issue: n3c_control_map does not have field names person_id but this field is referenced in later query. Probably intended to be control_person_id?

<img width="672" alt="image" src="https://user-images.githubusercontent.com/3923918/102396273-70350080-3f99-11eb-8a2d-d6d23219a401.png">


<img width="473" alt="image" src="https://user-images.githubusercontent.com/3923918/102396292-7b882c00-3f99-11eb-8db1-9a7f09ff0cf6.png">

**Comment by mgkahn** [comment]
Fixing the above 2 field names to valid name, the script runs successfully to completion. I don't know if these changes keeps the intended logic, which is too deep for my brain........

**Comment by empfff** [comment]
This is a good catch, this did not throw an error in other dialects b/c it was inside a "NOT IN" statement. We updated it in all the scripts. The change to make is to change case_person_id in the WHERE in the subquery to person_id. Let us know if we can clarify.
