### ISSUE TITLE
Oracle OMOP phenotype SQL missing comma

### ISSUE THREAD

**Issue by kirenotneb** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#174]
The Oracle OMOP phenotype SQL complains of a missing `FROM` clause due to a [missing comma at the beginning of line 745](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/blob/ed2d069a9cdddac917ff567cb3df7a05d31bab8b/PhenotypeScripts/N3C_phenotype_omop_oracle.sql#L748).

**Comment by empfff** [comment]
Fixed, thanks for the catch!
