### ISSUE TITLE
OMOP birthdates

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#176]
Need to adjust OMOP extract script to extract month and year of birth from full birthdate field, rather than selecting from year and month fields.

**Comment by mgkahn** [comment]
Why this change? Can you explain motivation/source of this post? 

Year and Month fields are **required** in OMOP CDM V5.3.1 Full birth_datetime field is **optional** in 5.3.1 and I suspect rarely filled in. There is no full birth_date field in 5.3.1. See: https://ohdsi.github.io/CommonDataModel/cdm531.html

**Comment by empfff** [comment]
Potential best-of-both-worlds solution: change function to a coalesce to pull year/month fields where populated, and check full birthdate field when they are null, in case that is filled in instead.

**Comment by empfff** [comment]
Consolidated into #181
