### ISSUE TITLE
Potential missing COVID measurements

### ISSUE THREAD

**Issue by mgkahn** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#177]
Cut-paste email from Melanie Philofsky. Focused on MEASUREMENT concept_ids. There are 60K measurement records using Colorado COVID concept_ids that are NOT present in the Phenotype 3.0 COVID measurement list.

**************************************************************************
<img width="866" alt="MissingCOVIDMeasurements0" src="https://user-images.githubusercontent.com/3923918/105905782-17b54200-5fe0-11eb-9437-d0d6291a83fe.png">
[N3C Covid test discrepency between N3C concept set and UCHealth data.txt](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/files/5876095/N3C.Covid.test.discrepency.between.N3C.concept.set.and.UCHealth.data.txt)
[N3C Covid test discrepency between N3C concept set and UCHealth data.txt](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/files/5876096/N3C.Covid.test.discrepency.between.N3C.concept.set.and.UCHealth.data.txt)

Hello Michael,

As I mentioned on Slack, I have some concerns about the N3C concept set for COVID-19 lab tests. I think some standard Measurement concept_ids for COVID-19 lab tests were inadvertently excluded. Now, these might have been excluded on purpose, but I want to bring them to your attention.

I am attaching the following:

1. N3C Covid test discrepency between N3C concept set and UCHealth data.txt: 
This has the N3C concept set for COVID-19 lab tests/Measurements taken from the N3C_phenotype_omop_bigquery.sql you forwarded to me. It also contains Melanie's concept set for COVID Measurements I created based on Kratos Measurement table COVID-19 lab test data. And then a list of concept_ids NOT IN N3C concept set.

2. N3C Covid tests NOT IN concept set
This is an excel of the COVID-19 concept_ids we have in our data but are not in the N3C concept set. It contains all attributes from the Concept table for the concept_ids

**Comment by mgkahn** [comment]
[N3C Covid test discrepency between N3C concept set and UCHealth data.txt](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/files/5876104/N3C.Covid.test.discrepency.between.N3C.concept.set.and.UCHealth.data.txt)

Second file for Issue #177

**Comment by kmkostka** [comment]
Actions:

- [ ] Update LOINC code table to include two valid LOINC codes that are not in our current phenotype but are valid
- [ ] Update OMOP measurement concept set to include the 4 additional concepts
- [ ] Cascade up to date phenotype script

**Comment by kmkostka** [comment]
@tannerzhang , let's coordinate on the last item here. It's ready for consumption into your lists.

**Comment by kmkostka** [comment]
Resolved.
