### ISSUE TITLE
COVID Test only patients

### ISSUE THREAD

**Issue by mgkahn** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#178]
Based on Phenotype 3.0 cohorts described here (https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/wiki/Latest-Phenotype) it seems possible to match patients whose only contact with the institution is for COVID screening and no other interaction. Our institution has opened up its COVID screening to the entire community, many of whom receive care and f/u elsewhere. Our EMR would not have any more information other than very basic demographics and the presence of the positive/negative test.

Colorado's EMR -> OMOP ETL **requires** at least one clinical face-to-face encounter to enter our RDW which prevents the above from happening (a lab or radiology-only event does not qualify as a face-to-face). 

Just a heads up to consider if this situation could actually be happening and if so could be an issue for downstream analytics.

**Comment by empfff** [comment]
I think that's okay, and is probably true of other institutions as well. That's a great example of why we can't use N3C for incidence/prevalence--we're definitely not getting everyone. I think it's reasonable to limit to patients who have had at least one encounter if that's how patients get into your RDW.
