### ISSUE TITLE
datepart() not valid in bigquery

### ISSUE THREAD

**Issue by mgkahn** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#186]
Not sure if fixable via SQLRender.  Datepart function used in ExtractScripts (lines 155,156) is not a valid GBQ function.

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/3923918/107715362-5c9dd180-6c8c-11eb-8f55-a846db81e0fe.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/3923918/107715514-ac7c9880-6c8c-11eb-95ff-f71dc978c508.png">
GBQ uses EXTRACT function: EXTRACT(part FROM date_expression)

How can I help?

**Comment by empfff** [comment]
Is there any chance you would be able to correct it and submit as a pull request? Our challenge is that we don't have an environment we can use to test changes to the GBQ script. Let us know if that would work.

Sorry for the bugs!

**Comment by mgkahn** [comment]
Pull request with fix submitted.

**Comment by mgkahn** [comment]
Pull request submitted.
M

**Comment by kmkostka** [comment]
Resolved in #188
