### ISSUE TITLE
Add new LOINC codes on phenotype-33 branch

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#206]
Need new LOINC codes added to ACT, TriNetX, and OMOP scripts. New codes are:

95542-7
95608-6
95609-4
95824-9
95825-6
95826-4
95970-0
95971-8
95972-6
95973-4
96091-4
96119-3
96120-1
96123-5
96448-6
96603-6

**Comment by kmkostka** [comment]
Pushed update for OMOP dialects change in LOINC codes and depreciation of dx_strong (#199).

**Comment by LoraLingrey-TriNetX** [comment]
TNX updates pushed.

**Comment by mim18** [comment]
ACT updates pushed

**Comment by kmkostka** [comment]
Released.
