### ISSUE TITLE
Are the directory contents screenshots updated?

### ISSUE THREAD

**Issue by riqi-rob-mcconeghy** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#220]
Hello! I am making an N3C extract, running through my checklist I see "Ensure Directory Structure is Correct." My directory contains additional files not pictured in your screenpics:

folder 1: data files subfolder, data counts, +extract validation, manifest
folder 2, "datafiles": (no dose era), +death, +device exposure, +n3c control map

note: "+" above indicates my code-run generated these files but they aren't pictured on your GH guide
also dose era was present in the screen pic but isn't on my end.

If I'm in the wrong here please let me know, just want to make sure I'm submitting the best data possible :)

**Comment by empfff** [comment]
Hi Rob! I think you're in good shape--the directory screenshots are probably a bit stale. Nothing you mention in your lists above sounds out of place. You're good to submit!
