### ISSUE TITLE
Additional LOINCs from PCORnet's list 

### ISSUE THREAD

**Issue by KellieMarie** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#25]
I compared the N3C phenotype to the PCORnet phenotype. The following LOINCs were included in the PCORnet list but not N3C. Consider for inclusion. 

94306-8 | SARS coronavirus 2 RNA panel -   Unspecified specimen by NAA with probe detection
94503-0 | SARS coronavirus 2 IgG and IgM   panel - Serum or Plasma Qualitative by Rapid immunoassay
94504-8 | SARS coronavirus 2 IgG and IgM panel - Serum or Plasma by   Immunoassay
94531-1 | SARS coronavirus 2 RNA panel -   Respiratory specimen by NAA with probe detection

**Comment by empfff** [comment]
These are panel/order codes--we will address on the group call on 5/7 as to whether we should add to the phenotype. I suspect it can't hurt. Thanks!

**Comment by empfff** [comment]
Codes added to phenotype v 1.4.
