### ISSUE TITLE
Fix extract mistake

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#31]
I realized a silly thing I did in the PCORnet extract scripts (which I have since fixed)--please check to see if my mistake trickled down to the other models! In the DATA_COUNTS table, I neglected to join to the N3C_COHORT table each time (and add the 1/1/2018 date range where it made sense), so I was just counting the number of rows in the base table rather than the N3C extract.

Please add to your code (you can use mine as an example) if you don't have this already. Thanks!

**Comment by kmkostka** [comment]
Completed for OMOP.

**Comment by rbrad8158** [comment]
- [ ] OMOP
- [ ] ACT
- [ ] PCORnet
- [ ] TriNetX
