### ISSUE TITLE
Translate all code to SQL Server

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#32]
Translate extract and phenotype code to SQL Server syntax.

**Comment by rbrad8158** [comment]
- [ ] OMOP
- [ ] ACT
- [ ] PCORnet
- [ ] TriNetX

**Comment by empfff** [comment]
OMOP doing their own, @evancol doing ACT, TriNetX not needed
