### ISSUE TITLE
Possible additional codes

### ISSUE THREAD

**Issue by johnl8888** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#4]
1. May incorporate the latest NLM SNOMED value sets (including COVID-19 and signs/symptoms, see attached)
2. In the ICD10 side, i.e. U072/U073 are also possible candidates, additional suspected ones like J00-J06, J09-J11, R092, R918, etc.; also CMS new HCPCS G2023, G2024
3. Not sure we need consider other COVID-19 severe complications - i.e. ARDS, Sepsis (unique pathway) and ventilator related?

[2.16.840.1.113762.1.4.1114.7.xlsx](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/files/4512067/2.16.840.1.113762.1.4.1114.7.xlsx)
[2.16.840.1.113762.1.4.1181.51.xlsx](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/files/4512074/2.16.840.1.113762.1.4.1181.51.xlsx)

**Comment by empfff** [comment]
Will add the new SNOMED codes in the next version of the phenotype.

For #2, these codes to my knowledge are not in ICD-10-CM, and would not ever appear in an EHR. Please correct me if I'm wrong there.

For #3, are you suggesting that those codes be added as inclusion criteria? Or, are you thinking that they will be needed for downstream analysis? Remember that no matter how patients are brought into the cohort, their comorbid conditions and codes will be brought into the datamart regardless.

**Comment by johnl8888** [comment]
For #2 - depending on the starting time how we pull the data, many initial cases in Feb. & early March 2020, COVID-19 patients might be diagnosed or coded similar to respiratory/flu related due to lacking of lab; beyond this initial stage window, codings may be gradually converged with broader lab tests. Should we pull those data within some specific time window to indicate those might be probable/possible cases? Again this is very new virus, lagged EHR data reflects our learning curve.

For #3 - I don't know the answer, the unique disease progression pathway & sudden onset of oxygen/ventilator demanding (related codes) may provide additional value for data pull, esp. those probable/possible cases. Another observation, for example, although CMS released the official MS-DRG for COVID-19 inpatient stays, I still observed the conventional Sepsis DRG being billed. We all know the conventional Sepsis phenotype & treatment options are quite different than COVID-19 induced Sepsis; another example is the L/H phenotypes during ICU treatment. Should we address such uniqueness in the COVID-19 phenotype?

**Comment by empfff** [comment]
New SNOMED codes added to new version of phenotype that will be released today. Thanks for providing!
