### ISSUE TITLE
Clean up stray OMOP files

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#46]
1. Clean up any unneeded files from the OMOPExporter folder.
2. Within \OMOPExporter\inst\sql\sql_server, make sure that the "generate_cohort.sql" and "source_extract_scripts.sql" files are running the logic as you expect and contain all the queries. The individual SQL files should then be removed.

**Comment by kmkostka** [comment]
Having an issue with this function:  inrows <- readLines(file(sqlFile, "r"))

getting "Error in file(sqlFile, "r") : [pathway] cannot open the connection"

Will continue to debug in the AM.
