### ISSUE TITLE
Wording Consistency

### ISSUE THREAD

**Issue by tannerzhang** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#5]
The first section nominated the four tiers as “lab-confirmed positive,” “lab-confirmed negative,” **“probable positive,”** and “possible positive"; and the next section of "Phenotype rules" writes as “lab-confirmed positive cases,” “lab-confirmed negative cases,” **“suspected positive cases,”** and “possible positive cases". Maybe either could be changed to keep the consistency.

**Comment by johnl8888** [comment]
On a different note - Will antibody test be classified in the lab-confirmed positive/negative tiers? Some past patient case reported as "lab-confirmed negative" but imaging (i.e. CT/x-ray) confirmed as COVID-19 pneumonia - do we treat those as "probable positive"? Is it any value to include imaging diagnosis in the phenotype? Similar puzzle is the existence of L/H phenotypes during ICU treatment. There're many unknowns, we need to design such unique phenotype definition so those unknowns can be uncovered in the downstream analysis.

**Comment by empfff** [comment]
Wording change will be in new phenotype to be released today, thanks! Comment from @johnl8888 opened as new Issue.
