### ISSUE TITLE
Update LOINC codes for v 1.5

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#51]
Phenotype 1.5 released, please update phenotype scripts.

- [x] PCORnet
- [x] ACT
- [x] OMOP
- [x] TriNetX

**Comment by DarrenWHenderson** [comment]
Should we be converting any internal Lab codes our Hospital is using to one of these LOINC codes, or one of the Positive/Negative UMLS codes? Or should we be adding our internal codes to the top union for the Lab phenotype? I'm playing catch-up here, my apologies.

**Comment by empfff** [comment]
Thanks for a great question! We defer to you as to whether you'd like to map your labs to LOINCs internally (as you suggest in your comment), or whether you want to send over your tests as-is, and allow the N3C Harmonization group to assign a LOINC to that test on your site's behalf. The result will be the same (the lab will be LOINC coded)--the coding could just happen at a different part in the process.

**Comment by mim18** [comment]
Darren in ACT if we don't know what the LOINC is we are using the UMLS codes.Its also helping us to normalize the value pos/neg/etc. In the V3 Ontology coming out today we are separating the coding into antibody and nucleic tests and will have 4 additional codes.  The UMLS codes are included in the phenotype scripts and will be updated later today.  If you use any local codes, make sure you add that code to the phenotype script.

**Comment by kmkostka** [comment]
Validated against OMOP vocab update.
