### ISSUE TITLE
Fix Date Format

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#52]
In documentation, OMOPExporter and Python Exporter

**Comment by empfff** [comment]
Fixed in documentation

**Comment by marshallclark** [comment]
@empfff can we change this to be all uppercase:
(Ex: unc_pcornet_20200504)
the SITE_ABBREV and CDM_NAME values are “UNC”  and “PCORNET”
