### ISSUE TITLE
GBQ errors with R package

### ISSUE THREAD

**Issue by mgkahn** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#56]
From Bujia.Zhang@cuanschutz.edu:
 
BigQuery SqlRender issues for N3C R package execution:

1. generate_cohort.sql: 
The statement: “create table #Codesets()” is processed by SqlRender into “create table ttav56kacodesets()” The post SQLRender statement is invalid because it is missing the dataset name in front of the table name. The correct output should be “create table [dataset name].ttav56kacodesets()”. The dataset name in this project could be @resultsDatabaseSchema. 
2. source_extract_scripts.sql
a.       Convert() function is not a BigQuery function and has not been mapped in the SqlRender replacement patterns . The extract script has CONVERT(VARCHAR(20),OBSERVATION_PERIOD_START_DATE, 120), after sqlrender, it's convert(STRING,observation_period_start_date, 120). 
This is the script we adjusted for BigQuery: format_datetime('%Y-%m-%d %H:%M:%S',datetime(observation_period_start_date))
b.       Date format for where clause is not been transformed to a valid BigQuery date format. The extract script has visit_start_date >= '1/1/20', BigQuery accepts visit_start_date >= '2018-01-01'
c.       Convert() and date add/subtract function. For the last query, extract script has CONVERT(VARCHAR(20), GETDATE() -2, 120) as UPDATE_DATE. First is the convert part, second is the data add/subtract part. Bigquery accepts the following format: format_datetime('%Y-%m-%d %H:%M:%S',datetime( date_add(CURRENT_DATE(), interval -2 day))) as UPDATE_DATE
3.	May or may not be an issue: The output file combines all columns into one excel column. For example, PERSON should have 15 columns from the source_extract_scripts.sql, the output csv file has only one column which includes all 15 columns separated by “|”.

**Comment by kmkostka** [comment]
Addressed in recent updates.
