### ISSUE TITLE
SITE_NAME is missing in the manifest table

### ISSUE THREAD

**Issue by stephanieshong** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#57]
The manifest table only contains the SITE_ABBREV and it is missing SITE_NAME. 
We use this field to set the site's full name in our data quality dashboard to generate the output files via the OMOP's DQDashboard. Could you add SITE_NAME field in the manifest table?

**Comment by empfff** [comment]
Two new manifest fields added for all but OMOP; need to confer with @rtmill on the best way to handle, so as not to break the R exporter.
