### ISSUE TITLE
SqlRender does not support CONVERT translation

### ISSUE THREAD

**Issue by konstjar** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#59]
There was reported [issue](https://github.com/OHDSI/SqlRender/issues/224) in SQLRender package about problem with `CONVERT` function. The problem is that this function is not [supported translations list](https://ohdsi.github.io/SqlRender/articles/UsingSqlRender.html#functions-and-structures-supported-by-translate-1)

The [code](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/blob/master/Exporters/OMOPExporter/inst/sql/sql_server/source_extract_scripts.sql#L39) is not able to be executed on some dialects.

**Comment by rtmill** [comment]
fixed by #69

**Comment by kmkostka** [comment]
Noted and future updates to package will adhere to supported translations list.
