### ISSUE TITLE
Feedback from UTH

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#6]
"To be included as a "suspected positive"/"probable positive" (over 50% patients should have COVID), the use of CPT code 86318 (infectious agent antibody) is going to potentially greatly skew these numbers. This code is used generically for many rapid infectious agent antibody tests. CPT 86328 is created specifically for COVID-19 rapid antibody testing. Again, they might think there could be miscoding here, but I would worry that this code is used extensively for other infectious agents and could affect the numbers. "

**Comment by empfff** [comment]
4/24 large phenotype call determined this code should remain in the phenotype, though very good to know it will likely result in false positives.

**Comment by remurphymd** [comment]
What is the rationale here? Was there someone clinically who felt that this will not impact the 50% goal for this category?
