### ISSUE TITLE
MANIFEST table in N3C_extract_V1_0_act_mssql.sql

### ISSUE THREAD

**Issue by DarrenWHenderson** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#63]
The site instructions [here](https://github.com/National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition/wiki/Site-Instructions:-ACT-Data-Model) describe the last three columns of the MANIFEST table (RUN_DATE, UPDATE_DATE, NEXT_SUBMISSION_DATE) and the demo data has the date only, dropping the timestamp. The extract script produces the full datetime value. If you don't want sites using the mssql file to upload time in these fields, the script needs to be altered as below (alter varchar(20) to varchar(10) in the first member of the CONVERT function): 

`CONVERT(VARCHAR(10), GETDATE(), 120) as RUN_DATE,`
`CONVERT(VARCHAR(10), GETDATE() -2, 120) as UPDATE_DATE,`
`CONVERT(VARCHAR(10), GETDATE() +3, 120) as NEXT_SUBMISSION_DATE;`

Alternative (date format 23 from [here](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15)). Using this, any length for varchar >= 10 would be fine.

`CONVERT(VARCHAR(10), GETDATE(), 23) as RUN_DATE,`
`CONVERT(VARCHAR(10), GETDATE() -2, 23) as UPDATE_DATE,`
`CONVERT(VARCHAR(10), GETDATE() +3, 23) as NEXT_SUBMISSION_DATE;`

Both tested on: Microsoft SQL Server 2016 (SP1-CU7-GDR) (KB4057119) - 13.0.4466.4 (X64)   Dec 22 2017 11:25:00   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by empfff** [comment]
Waiting to determine whether harmonization team is not able to accept timestamps, or whether we should change our spec to allow them. (Will make code maintenance easier.)
