### ISSUE TITLE
pyodbc not installed

### ISSUE THREAD

**Issue by hlehmann17** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#75]
Your installation may not have pyodbc: You may need to: pip3 install pyodbc

similar to paramiko

**Comment by LisaOKeefe1** [comment]
Thanks for the feedback  @hlehmann17 
@empfff have just assigned you as an FYi.

**Comment by empfff** [comment]
Thanks! @rbrad8158 is making a change to check for missing components, stay tuned.

**Comment by empfff** [comment]
component added to check for this package!
