### ISSUE TITLE
Numeric and datetime values in extracted files not double-quote protected

### ISSUE THREAD

**Issue by jphuong** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#79]
I used the R exporter for omop and mssql. I just inspected my extracted files and noticed the integer and datetime values are not double-quoted. For instance, in the person file, the gender_source_value is double-quote protected eg "F", but the person_id is not double-quote protected. I wonder if I had missed a setting.

**Comment by jphuong** [comment]
This fix seems straight-forward. To get all columns in the output table to be double-quote protected, change the result matrix to character datatype just before file writing. 

In Line 97 of extractCohortData.R, wrap the sql query result with an sapply using as.character assertion. Line 97 could look like the following:
**result = sapply(result, as.character)**

**Comment by empfff** [comment]
Worked with  harmonization team and determined that it's okay to not quite numeric and date fields.
