### ISSUE TITLE
PK checker for OMOP and ACT

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#87]
In R: Replicate the PK checker logic from the latest version of the Python script. See comment that @marshallclark will leave below for that logic. -- assigned to @rtmill 

In OMOP extract SQL: Replicate the --VALIDATION_SCRIPT block from the PCORnet MS SQL script, such that it produces similar output -- assigned to @kmkostka 

In ACT extract SQL: Replicate the --VALIDATION_SCRIPT block from the PCORnet MS SQL script, such that it produces similar output -- assigned to @empfff

**Comment by empfff** [comment]
Completed for ACT.

**Comment by marshallclark** [comment]
This is what i'm doing in the python script:

when parsing the extract scripts into individual sql blocks, look for this tag:  VALIDATION_SCRIPT
if the sql block has that tag associated with it in the sql, treat that block as a validation script
validation sql blocks will also have to have the OUTPUT_FILE: tag, like the other extract sql blocks

I'm allowing for multiple validation scripts

The first sql blocks to export/extract, are the validation scripts

for each validation script
* run the sql
* export the data
* if any rows are returned ( row count > 0) then:
* * put an error message that validation failed for script name (output file name), see results in (output file name)
* * exit the program immediately

**Comment by kmkostka** [comment]
Completed for OMOP. Merge pending second set of eyes.

**Comment by rtmill** [comment]
completed OMOP by #93
