### ISSUE TITLE
Add negative flu test as selection criterion

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#9]
Suggestion from Ken Gersing:

Are we looking for influenza with a negative results as part of the phenotype? We are being told a lot of folks early on pre LOINC Covid code were being tested for influenza and many the neg folks are probably COVID patients

**Comment by rbrad8158** [comment]
If you look for neg influenza, you should check for anything on the respiratory virus profile: Flu A&B, RSV A&B, etc.

**Comment by remurphymd** [comment]
Are you asking for patients with an ICD-1o or SNOMED for an influenza-related diagnosis that does not have a positive viral result for another pathogen (w agree we need to check all others). But then add these patients to the probable positive COVIID-19.

Might give some thought as to the start date of this criteria. Might not be appropriate until late February 2020.

**Comment by empfff** [comment]
We are investigating making this change; large phenotype call seemed to agree that it's a good idea. It is a significant change, so will leave this issue open until we are able to comprehensively gather flu LOINC codes and other criteria.

**Comment by empfff** [comment]
In the interest of keeping the cohort size manageable, we will not add this.
