### ISSUE TITLE
Update ACT documentation to reflect validation and code map changes

### ISSUE THREAD

**Issue by mim18** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#91]
Per Darren Henderson on Slack
The site instructions (at least for ACT haven't reviewed others) have not been updated to include the new EXTRACT_VALIDATION.csv, ACT_STANDARD2LOCAL_CODE_MAP.csv, or N3C_VOCAB_MAP.csv files. I'm assuming they should end up alongside the DATA_COUNT.csv and MANIFEST.csv files outside the DATAFILES folder, correct? (

**Comment by KellieMarie** [comment]
@mim18 I had this on my to do list for this week. I can still work on this but don't want to duplicate effort. Let me know.

**Comment by empfff** [comment]
I will take care of the written part of this. I added stuff about the N3C_VOCAB_MAP table to the ACT docs last week; I just neglected to mention the other new tables. 

@KellieMarie if you could just do the screenshot part, I think we'll be good.

**Comment by KellieMarie** [comment]
@empfff I've made the changes in the text before seeing this but if you want to take a look and review, that would be great.
