### ISSUE TITLE
Community Issue--Help us with our phenotype algorithm!

### ISSUE THREAD

**Issue by empfff** [National-COVID-Cohort-Collaborative/Phenotype_Data_Acquisition#95]
Please leave a comment below if you are able and willing to run a couple of quick counts at your site:

1. count of patients from 4/1/2020 to present with Z11.59 (diagnosis) AND U07.1 (diagnosis).
2. count of patients from 4/1/2020 to present with Z11.59 (diagnosis) AND NOT U07.1 (diagnosis).
3. (This one's a little more work, so this is a bonus...) count of patients from 4/1/2020 to present with Z11.59 (diagnosis) AND positive covid test. (LOINC codes for covid tests can be found in our phenotype documentation, if that helps.)

We appreciate any information you might be able to offer! If you'd prefer to email me responses rather than post here, no problem--you can contact me at epfaff at email dot unc dot edu.

**Comment by DarrenWHenderson** [comment]
1. 9
2. 1357
3. 10
